In [160]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


[[ 1  2  3  4  5]
 [ 4  6  8 10 12]
 [ 3  6  9 12 15]
 [ 8 12 16 20 24]
 [10 15 20 25 30]]


In [144]:
# loading the training and testing data
ccpp_train = np.genfromtxt('train.csv', delimiter = ',')
x_train = ccpp_train[:, 0:ccpp_train.shape[1]-1]
y_train = ccpp_train[:, ccpp_train.shape[1]-1]
x_test = np.genfromtxt("test.csv", delimiter = ",")
print(ccpp_train.shape)
print(y_train.shape)

(7176, 5)
(7176,)


In [145]:
# printing the data
print(ccpp_train)
print(type(ccpp_train))
# print(x_train)

[[   8.58   38.38 1021.03   84.37  482.26]
 [  21.79   58.2  1017.21   66.74  446.94]
 [  16.64   48.92 1011.55   78.76  452.56]
 ...
 [  29.8    69.34 1009.36   64.74  437.65]
 [  16.37   54.3  1017.94   63.63  459.97]
 [  30.11   62.04 1010.69   47.96  444.42]]
<class 'numpy.ndarray'>


In [146]:
df = pd.DataFrame(x_train)
print(df)

          0      1        2      3
0      8.58  38.38  1021.03  84.37
1     21.79  58.20  1017.21  66.74
2     16.64  48.92  1011.55  78.76
3     31.38  71.32  1009.17  60.42
4      9.20  40.03  1017.05  92.46
...     ...    ...      ...    ...
7171   9.32  37.73  1022.14  79.49
7172  11.20  41.38  1021.65  61.89
7173  29.80  69.34  1009.36  64.74
7174  16.37  54.30  1017.94  63.63
7175  30.11  62.04  1010.69  47.96

[7176 rows x 4 columns]


In [147]:
print(df[1])

0       38.38
1       58.20
2       48.92
3       71.32
4       40.03
        ...  
7171    37.73
7172    41.38
7173    69.34
7174    54.30
7175    62.04
Name: 1, Length: 7176, dtype: float64


In [148]:
print(df.columns)

RangeIndex(start=0, stop=4, step=1)


In [149]:
print(df.values)

[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]


In [150]:
# adding dummy data to training data
df = pd.DataFrame(x_train)
N = x_train.shape[1]
count =1
for i in range(N):
    for j in range(i, N):
        df[count] = df[df.columns[i]] * df[df.columns[j]]
        count += 1

for i in range(N):
    for j in range(i, N):
        for k in range(j, N):
            df[count] = df[df.columns[i]]*df[df.columns[j]]*df[df.columns[k]]
            count += 1

x_train = df.values

# adding dummy data to testing data
df = pd.DataFrame(x_test)
N = x_test.shape[1]
count =1
for i in range(N):
    for j in range(i, N):
        df[count] = df[df.columns[i]] * df[df.columns[j]]
        count += 1

for i in range(N):
    for j in range(i, N):
        for k in range(j, N):
            df[count] = df[df.columns[i]]*df[df.columns[j]]*df[df.columns[k]]
            count += 1

x_test = df.values

In [151]:
# feature Scaling
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [152]:
# step_gradient - find the new regression coefficients
def step_gradient(x, y, learning_rate, m):
    M = x.shape[0]
    m_slope = (-2/M)*(((y - (x*m).sum(axis=1)).reshape(-1, 1))*x).sum(axis=0)
    # brr = np.array([[1, 2, 3, 4, 5],[2,3,4,5,6],[1, 2, 3, 4, 5],[2,3,4,5,6],[2,3,4,5,6]])
    # arr = np.array([[1], [2], [3], [4], [5]])
    # print(arr*brr)
    # print(((y - (x*m).sum(axis=1)).reshape(-1, 1)).shape)
    # print(x.shape)
    m = m - learning_rate * m_slope
    return m

In [153]:
# cost - finding the error on trainig_data
def cost(x, y, m):
    # brr = np.array([[1, 2, 3, 4, 5],[2,3,4,5,6]])
    # arr = np.array([1, 2, 3, 4, 5])
    # print(brr*arr)
    # print((brr*arr).sum(axis=0))
    # print((brr*arr).sum(axis=1))
    # #here axis is 1 for row as this axis is in numpy
    # #whereas in genral axis=1 is for column as this axis is in pandas
    return ((y - (x*m).sum(axis=1)) ** 2).mean()

In [154]:
# generic_gd - calculate regression coefficient with specified learning_rate and num_iterations
def generic_gd(x, y, learning_rate, num_iterations):
    m = np.zeros(x.shape[1])
    for i in range(num_iterations):
        m = step_gradient(x, y, learning_rate, m)
        print(i, "Cost :", cost(x, y, m))
    return m

In [155]:
# run - run gradient descent on training data
def run(x, y):
    df = pd.DataFrame(x)
    df[x.shape[1]] = 1
    x = df.values
    learning_rate = 0.009
    num_iterations = 50
    m = generic_gd(x, y, learning_rate, num_iterations)
    print(m)
    return m
m = run(x_train, y_train)

(7176, 32)
(7176, 1)
0 Cost : 199316.62803392168
(7176, 32)
(7176, 1)
1 Cost : 192181.65286189417
(7176, 32)
(7176, 1)
2 Cost : 185319.71312602583
(7176, 32)
(7176, 1)
3 Cost : 178706.7686780351
(7176, 32)
(7176, 1)
4 Cost : 172330.75010614117
(7176, 32)
(7176, 1)
5 Cost : 166182.49187618188
(7176, 32)
(7176, 1)
6 Cost : 160253.70605348563
(7176, 32)
(7176, 1)
7 Cost : 154536.52311605553
(7176, 32)
(7176, 1)
8 Cost : 149023.38179800153
(7176, 32)
(7176, 1)
9 Cost : 143706.99688983784
(7176, 32)
(7176, 1)
10 Cost : 138580.34466178046
(7176, 32)
(7176, 1)
11 Cost : 133636.65247373437
(7176, 32)
(7176, 1)
12 Cost : 128869.3895724245
(7176, 32)
(7176, 1)
13 Cost : 124272.2583990199
(7176, 32)
(7176, 1)
14 Cost : 119839.18624785978
(7176, 32)
(7176, 1)
15 Cost : 115564.31723231214
(7176, 32)
(7176, 1)
16 Cost : 111442.00453978844
(7176, 32)
(7176, 1)
17 Cost : 107466.80296401307
(7176, 32)
(7176, 1)
18 Cost : 103633.4617042835
(7176, 32)
(7176, 1)
19 Cost : 99936.91742209315
(7176, 32)
(717

In [156]:
# predict - predicting values for x_test
def predict(x,m):
    return (x*m).sum(axis=1)

In [157]:
df = pd.DataFrame(x_test)
df[x_test.shape[1]] = 1
x_test = df.values
y_pred = predict(x_test, m)
print(y_pred)

[286.05262866 285.92163677 255.54829887 ... 262.87032496 265.12481217
 269.52912406]


In [158]:
np.savetxt('Predictions_ccpp.csv',y_pred, fmt = "%.8f")